name: Deploy to Hosting

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Deploy via SCP
              run: |
                  scp -o StrictHostKeyChecking=no -r ./berserk-helper/* ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}
              env:
                  SSH_PASSWORD: ${{ secrets.SSH_PRIVATE_KEY }}
              shell: bash
