name: Deploy to Hosting

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy over SSH
              run: |
                  echo "sshpass -p ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}" >> test.txt
                  cat test.txt
                  rm test.txt

            # run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'ls -la'
