name: Deploy to Hosting

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy over SSH
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: 22
                  script: whoami

            # run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} 'ls -la'
