name: Deploy to Hosting

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Deploy over SSH
              uses: Dylan700/sftp-upload-action@latest
              with:
                  server: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: 22
                  uploads: |
                      ./berserk-helper/test.txt => ${{ secrets.REMOTE_PATH }}
