name: Deploy to Hosting

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: copy file via ssh password
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: ${{ secrets.REMOTE_USER }}
                  password: ${{ secrets.SSH_PASSWORD }}
                  port: ${{ secrets.REMOTE_PORT }}
                  script: |
                      whoami
                      ls
                      git --version
                  # source: "./berserk-helper/*"
                  # target: ${{ secrets.REMOTE_PATH }}
